export enum Configuration {
  SERVER_HOST = 'SERVER_HOST',
  SERVER_PORT = 'SERVER_PORT',
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MONGODB_DATABASE_NAME = 'MONGODB_DATABASE_NAME',
  MONGODB_AUTH_SOURCE = 'MONGODB_AUTH_SOURCE',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
}
