export enum Configuration {
  // ips and ports of stuff
  SERVER_HOST = 'SERVER_HOST',
  SERVER_PORT = 'SERVER_PORT',
  CLIENT_ROOT = 'CLIENT_ROOT',
  CLIENT_PORT = 'CLIENT_PORT',

  // database stuff
  MONGODB_HOST = 'MONGODB_HOST',
  MONGODB_PORT = 'MONGODB_PORT',
  MONGODB_USERNAME = 'MONGODB_USERNAME',
  MONGODB_PASSWORD = 'MONGODB_PASSWORD',
  MONGODB_DATABASE_NAME = 'MONGODB_DATABASE_NAME',
  MONGODB_AUTH_SOURCE = 'MONGODB_AUTH_SOURCE',

  // redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  // email
  EMAIL_FROM_ADDRESS = 'EMAIL_FROM_ADDRESS',
  EMAIL_SMTP_HOST = 'EMAIL_SMTP_HOST',
  EMAIL_SMTP_PORT = 'EMAIL_SMTP_PORT',
  EMAIL_SMTP_USERNAME = 'EMAIL_SMTP_USERNAME',
  EMAIL_SMTP_PASSWORD = 'EMAIL_SMTP_PASSWORD',

  // JWT
  JWT_AUTH_TOKEN_EXPIRATION = 'JWT_AUTH_TOKEN_EXPIRATION',
  JWT_VERIFY_EMAIL_TOKEN_EXPIRATION = 'JWT_VERIFY_EMAIL_TOKEN_EXPIRATION',
  JWT_EMAIL_TOKEN_EXPIRATION = 'JWT_EMAIL_VERIFICATION_TOKEN_EXPIRATION',

  // secrets
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
}
